// Generated by nuxt-seo-utils.assets

declare module '#app' {
  import { HeadEntry, HeadTag } from '@unhead/vue/types'

  interface RuntimeNuxtHooks {
    'head:tags': (tag: HeadTag[]) => Promise<void> | void
    'head:entries': (entries: HeadEntry[]) => Promise<void> | void
  }
}
declare module '@unhead/schema' {

  type PublicFiles = '/apple-touch-icon.png' | '/favicon-96x96.png' | '/favicon.ico' | '/logo.png' | '/og-image.jpg' | '/site.webmanifest' | '/web-app-manifest-192x192.png' | '/web-app-manifest-512x512.png' | '/fonts/BauhausStd-Demi.woff2' | '/fonts/Geist-Black.woff2' | '/fonts/Geist-Bold.woff2' | '/fonts/Geist-Medium.woff2' | '/fonts/Geist-Regular.woff2' | '/fonts/Geist-SemiBold.woff2' | '/fpmp4/fp1.mp4' | '/fpmp4/fp2.mp4' | '/fpmp4/fp3.mp4' | '/fpmp4/fp4.mp4' | '/fpmp4/fp5.mp4' | (string & Record<never, never>)
  type JsFiles = (string & Record<never, never>)

  interface SchemaAugmentations {
    link: import('@unhead/schema').UserTagConfigWithoutInnerContent & {
      href: PublicFiles
    }
    script: import('@unhead/schema').TagUserProperties & {
      src: JsFiles
    }
  }
}
export {}
